name: Build

on:
  workflow_dispatch:
    inputs:
      publishReleases:
        description: 'Publish to Releases'
        required: false
        default: 'true'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2

      - name: Get Library Version
        id: get_version
        run: |
          lib_version="$(./gradlew properties | grep ^version: | cut -d' ' -f2)"
          echo "Library Version: $lib_version"
          echo "version=$lib_version" >> $GITHUB_OUTPUT
          echo "v_version=v$lib_version" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build Release Package
        run: |
          ./gradlew releaseProcessingLib --no-daemon

      - name: Build Android Release Package
        run: |
          ./gradlew releaseProcessingLib -PoutputNamePostfix=-android -PjavacppPlatform=android-arm,android-arm64,android-x86,android-x86_64 --no-daemon

      - name: Build Bare Release Package
        run: |
          ./gradlew releaseProcessingLib -Pdisable-fatjar -Pbare -PoutputNamePostfix=-bare --no-daemon

      # upload dist
      - name: Upload binaries to release
        if: ${{ github.event.inputs.publishReleases == 'true' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/*
          tag: "${{ steps.get_version.outputs.v_version }}"
          release_name: "Version ${{ steps.get_version.outputs.version }}"
          body: "Prebuilt opencv-processing libs version ${{ steps.get_version.outputs.version }}."
          overwrite: true
          file_glob: true
          prerelease: true